resolver: lts-11.4

packages:
- .

allow-newer: true

extra-deps:
- gl-capture-0.1.0.0
- numeric-tools-0.2.0.1
- polynomial-0.7.3
- hip-1.5.3.0
- Chart-diagrams-1.8.3
- SVGFonts-1.6.0.3
- diagrams-core-1.4.1
- diagrams-lib-1.4.2.2
- diagrams-postscript-1.4.1
- diagrams-svg-1.4.2
- diagrams-solve-0.1.1
- dual-tree-0.2.2
- combinat-0.2.9.0
- permutation-0.5.0.5
